Book library homepage using Javascript.
Abdoulaye-Thespy/Library-JS pull request #2
Opened 2020-08-31 19:48 UTC by Abdoulaye-Thespy

In this milestone, I create a Library book app where I can

2020-08-31 23:46 UTC, shloch requested changes
## Hello @Abdoulaye-Thespy 

Great job with your work
App works perfect to about 98%
Let's get to some debugging

### [changes required]
- "empty" form can be submitted, please control this
![lib](https://user-images.githubusercontent.com/40712459/91779059-5808c380-ebec-11ea-8756-0820f5e27c79.gif)

- your `js` file is not well formatted, please work on making that code clean

- plenty `console.log` to remove...take care of that

2020-08-31 23:46 UTC, shloch commented on index.js
> +
- control form values before you submit/push (security)
- remove `console.log`  [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/console_log_requirement.png)]

2020-08-31 23:46 UTC, shloch commented on index.js
> +
- you didn't also delete book from local storage

2020-08-31 23:46 UTC, shloch commented on index.js
> +     console.log(readstatus);
remove `console.log`

2020-08-31 23:46 UTC, shloch commented on index.js
> +}
- this code is not well formatted, please check linters again (or format cleanly)
- remove `console.log`

2020-09-01 19:01 UTC, uryelah requested changes
Hi **Abdoulaye Razak**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job! Now just make sure your linter checks are all passing.

Check the pointers below and keep on coding! 🏃 💨 

# Required Changes 🏗️ 🐛 💡

- [ ] Make sure there are no linter errors being outputted by the Github Actions checker.

- [ ] I know you added the .gitignore with node_modules but make sure to also delete de node_modules directory from your repo. 

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-09-02 04:36 UTC, bellom approved these changes
## Hi @Abdoulaye-Thespy  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-11-14 06:45 UTC, merged